### ISSUE TITLE
Cartesi CLI error. I get "SQLite3Error: Could not open the database "database.db" when I run "cartesi build" on this repo

### ISSUE THREAD

**Issue by ETIM-PAUL** [doiim/cartesi-ts-sqlite#1]
<img width="779" alt="Screen Shot 2024-05-16 at 5 40 28 PM" src="https://github.com/doiim/cartesi-ts-sqlite/assets/12428501/998187b9-8f24-4abb-a626-0312a12c8379">

**Comment by filipesoccol** [comment]
Will take a look in this.
